### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by zmfb039** [Kalaborative/binance-bot#4]
I can get the bot to run, i enter my symbol and get this error. Any ideas?

  File "C:/Users/Alan/.spyder-py3/binance-bot-master/binance_bot.py", line 78, in <module>
    most_recent = klines.pop()

IndexError: pop from empty list

**Comment by Kalaborative** [comment]
What did you input as the symbol?

**Comment by zmfb039** [comment]
Hi thanks very much for replying.  I tried 

Welcome! type 'STOP' to stop
Enter a symbol.
> ETHBTC

then pressed enter and got

Traceback (most recent call last):
  File "C:\Users\......etc etc
master\binance_bot.py", line 78, in <module>
    most_recent = klines.pop()
IndexError: pop from empty list

**Comment by ghost** [comment]
Welcome! type 'STOP' to stop
Enter a symbol.
BNBBTC
Traceback (most recent call last):
File "binance_bot.py", line 78, in <module>
most_recent = klines.pop()
IndexError: pop from empty list


Any help fixing this please

Running windows 7 x64 with python 3.6.0

**Comment by k1ng69** [comment]
Change this line:

klines = client.get_historical_klines(sym, Client.KLINE_INTERVAL_1MINUTE, "1 min ago")

to this:

klines = client.get_historical_klines(sym, Client.KLINE_INTERVAL_1MINUTE, "1 min ago UTC")
